### ISSUE TITLE
Using Claw with (i,j,levs) variables: how and best practices

### ISSUE THREAD

**Issue by mathomp4** [claw-project/claw-compiler#575]
Another general question as I try to learn Claw. I have successfully reproduced the `mo_column` SCA example from the documentation using `clawfc` (modulo issue #574) so if nothing else, I know I built the package correctly.

My next question is: can this example be moved from 2-d to 3-d? That is instead of:
```fortran
  REAL, DIMENSION(20,60) :: q, t  ! Fields as declared in the whole model
  INTEGER :: nproma, nz           ! Size of array fields
  INTEGER :: p                    ! Loop index
```
can it become:
```fortran
  REAL, DIMENSION(4,5,60) :: q, t  ! Fields as declared in the whole model
  INTEGER :: nproma, npromb, nz           ! Size of array fields
  INTEGER :: p, j                    ! Loop index
```
I ask because the software I want to try Claw out on is (i,j,k) on the outside of our column physics routines and not (i,k).

I tried doing this naively:
```fortran
  !$claw sca forward
  DO p = 1, nproma
  DO j = 1, npromb
    CALL compute_column(nz, q(p,j,:), t(p,j,:))
  END DO
  END DO
```
and with enough trial-and-error, I also added a `promb` line a la `proma` to `mo_column.f90`:
```
    !$claw define dimension proma(1:nproma) &
    !$claw define dimension promb(1:npromb) &
    !$claw sca
```
And, after adding `nproma` and `npromb` to the transformed call (see #574), it seems to work.

So two questions:
1. Did I do this correctly?
2. Did I do this _the right way_?

The fact that it works makes me think, well, didn't screw up too badly so the first question isn't a "No". 

But, I'm wondering for question two if there is some fancy Claw way I don't know of where I should be fusing or jamming my two horizontal loops during the transform? That is after transform you pass in 3-d variables, but inside they are 2-d variables of (nproma*npromb,nz) shape/size?

**Comment by clementval** [comment]
@mathomp4 It is more or less the idea. Can you show me you final example so I can give you more comment. 

The two horizontal loop can be collapse (at least for OpenACC on GPU) by playing with the configuration directly in `<install_path>/etc/claw-default.xml` and you can change the value of `accelerator_collapse` from `false` to `true`. 

You can also change this directly on the command line with `-x=accelerator_collapse:true` for example.
