### ISSUE TITLE
Path to Fortran .mod files

### ISSUE THREAD

**Issue by aoloso** [claw-project/claw-compiler#576]
Description of the issue in few words.
I have a code that has a "use " statement for a Fortran module. The ".mod" file for the module exists. How do I point "clawfc" to that location? "-I" works for regular include files but not for ".mod" files.

**Comment by clementval** [comment]
You can use the `-J` option but you need the path to the source. `.mod` file are not compatible between compilers. If you need standard module such as MPI or NetCDF, look at the omni-mod-pool in the claw-project org.

**Comment by aoloso** [comment]
Thanks!
