### ISSUE TITLE
Issues with getting the dependencies

### ISSUE THREAD

**Issue by paklui** [claw-project/claw-compiler#585]
Hi, while trying to build the claw-compile for the first time, I am running into some issues with getting some dependencies. 

```
[ivy:retrieve]          ::::::::::::::::::::::::::::::::::::::::::::::
[ivy:retrieve]          ::          UNRESOLVED DEPENDENCIES         ::
[ivy:retrieve]          ::::::::::::::::::::::::::::::::::::::::::::::
[ivy:retrieve]          :: commons-cli#commons-cli;1.3.1: not found
[ivy:retrieve]          :: org.antlr#antlr4;4.7: not found
[ivy:retrieve]          :: junit#junit;4.12: not found
[ivy:retrieve]          :: net.consensys.cava#cava-toml;0.3.1: not found
[ivy:retrieve]          :: org.jacoco#org.jacoco.ant;0.8.2: not found
[ivy:retrieve]          :: org.ow2.asm#asm;6.2.1: not found
[ivy:retrieve]          ::::::::::::::::::::::::::::::::::::::::::::::
[ivy:retrieve] :::: ERRORS
[ivy:retrieve]  SERVER ERROR: HTTPS Required url=http://repo1.maven.org/maven2/commons-cli/commons-cli/1.3.1/commons-cli-1.3.1.pom
[ivy:retrieve]  SERVER ERROR: HTTPS Required url=http://repo1.maven.org/maven2/commons-cli/commons-cli/1.3.1/commons-cli-1.3.1.jar
[ivy:retrieve]  SERVER ERROR: HTTPS Required url=http://repo1.maven.org/maven2/org/antlr/antlr4/4.7/antlr4-4.7.pom
[ivy:retrieve]  SERVER ERROR: HTTPS Required url=http://repo1.maven.org/maven2/org/antlr/antlr4/4.7/antlr4-4.7.jar
[ivy:retrieve]  SERVER ERROR: HTTPS Required 
```
[logs.error-omni-compiler-maven.txt](https://github.com/claw-project/claw-compiler/files/4418428/logs.error-omni-compiler-maven.txt)

build steps:

```
export JAVA_HOME=/usr/lib/jvm/java-8-openjdk-amd64
export JRE_HOME=/usr/lib/jvm/java-8-openjdk-amd64/jre
export PATH=/usr/lib/jvm/java-8-openjdk-amd64/jre/bin:${PATH}
git submodule init
git submodule update --remote
rm -fr build && mkdir build && cd build
cmake .. -DCMAKE_INSTALL_PREFIX=${BASE_DIR}/install 
make -j install
```

Looking at the given errors, I need to change the url to https, but I coudln't find the place to replace it. The only place that seems to be place to change to https is this line in the file (./cx2t/common-targets.xml) but doesn't appear to have an effect.
```
src="https://repo1.maven.org/maven2/org/apache/ivy/ivy/2.3.0/ivy-2.3.0.jar"/>
```

The file where these jar/pom files are defined (cx2t/ivy.xml) doesn't appear to have an option to define https.

I attempted to get the files using the scripts/offline but it has the same error.

[log.claw-compiler-offline.txt](https://github.com/claw-project/claw-compiler/files/4418430/log.claw-compiler-offline.txt)

I could download these .jar/.pom files elsewhere (or offline) and copy back to this system, but I do not know where these files need to be. 

Please let me know if you have some suggestions. Thanks in advance.

**Comment by clementval** [comment]
PR #584 should solve this issue. Can you give it a try with a fresh cloned repo?

**Comment by paklui** [comment]
Thanks @clementval ! seems like it's working now by your change to upgrade ivy to 2.5.0

**Comment by clementval** [comment]
Good to know @paklui. Thanks for your report.
