### ISSUE TITLE
Wrong name of the tag for v2.0.2

### ISSUE THREAD

**Issue by skosukhin** [claw-project/claw-compiler#591]
Could you, please, rename the version tag `8c012d5` to `v2.0.2`? 

See: https://github.com/claw-project/claw-compiler/tags

**Comment by skosukhin** [comment]
@clementval I would like to use tags instead of commits here: https://github.com/spack/spack/blob/33e8dcad993968e47560bbc929a3ef4a38de0405/var/spack/repos/builtin/packages/claw/package.py#L18-L25
Is it possible to rename the tag for `v2.0.2`?

**Comment by clementval** [comment]
@skosukhin I'm not sure we can rename it but we can certainly make a tag of the tag with the correct name.

**Comment by clementval** [comment]
@skosukhin The tag is created here https://github.com/claw-project/claw-compiler/releases/tag/v2.0.2
