### ISSUE TITLE
[rfc] CLAW SCA start of parallel region to start at directive position

### ISSUE THREAD

**Issue by clementval** [claw-project/claw-compiler#601]
Current situation: 

When using `!$claw sca` with the GPU target in a subroutine, the start of the parallel region (horizontal loop insertion) is determined automatically to be at the start of the executable statements sections. There are some cases where some executable statements (e.g. assign statement) are skipped because they are known to be forbidden in OpenACC or OpenMP parallel/target offload region. 

Proposal: 

As user requested, we would like to propose to start the parallel region where the `!claw sca` directive is placed. This would give more control to the end-user if they wants some executable statements outside of the parallel region. 

Any comments on this before we implement something? @lxavier @FrostyMike

**Comment by lxavier** [comment]
sounds good to me - do you think we would need to adapt something in JSBACH once this feature would be implemented

**Comment by clementval** [comment]
@lxavier It should not change the behavior in 99% of the use case. In a typical SCA subroutine, the `claw sca` directive is placed between the declaration section and the executable section of the code. So in those case the behavior will be unchanged. 

As far as I remember, JSBACH should be in these 99% of cases and you should not have to change anything. I'll propose a PR for this change and you can test before we merge anything.

**Comment by lxavier** [comment]
good for me
